# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('app_id', models.CharField(choices=[(b'IOS_ALERT', b'IOS_ALERT'), (b'IOS_MATE', b'IOS_MATE')], max_length=15)),
                ('downloaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
