# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_remove_worldborder_mpoly'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborder',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='fips',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso2',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='pop2005',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='region',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='subregion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='un',
            field=models.IntegerField(),
        ),
    ]
